@startuml

class App {}

class FileProcessing {
    +{static}namesList : List
    +{static}numberOfNames : int

    +{static}readFilesNames()
    +{static}sortNames()
    +{static}outputFiles()
}

App o--> FileProcessing




@enduml